### ISSUE TITLE
Preprocessing data is lack of some codes?

### ISSUE THREAD

**Issue by Wietc** [NEXTLab-ZJU/wuyun#2]
I found that in the mdp_wuyun.py, a variable doesn't be used
`dst_dir_skeleton = os.path.join(dst_dir, '8_skeleton')`
but the step of code just include "step 07"
And I found that when I try to run the modules/build_dictionary.py, the data I needed don't be created.

**Comment by Xinda-Wu** [comment]
1. we move the melodic extract method to the dictionary ./preprocessing/utils/melodic_skeleton.
2. make sure your saving path, and try again!
